project_id = "dhufwdxxfbahovnmjgrc"

# Google Authentication Setup Instructions
# First, get your access token from https://supabase.com/dashboard/account/tokens
# export SUPABASE_ACCESS_TOKEN="your-access-token"
# export PROJECT_REF="your-project-ref"

# Update auth config to enable Google provider
# curl -X PATCH "https://api.supabase.com/v1/projects/$PROJECT_REF/config/auth" \
#   -H "Authorization: Bearer $SUPABASE_ACCESS_TOKEN" \
#   -H "Content-Type: application/json" \
#   -d '{
#     "external_google_enabled": true,
#     "external_google_client_id": "your-google-client-id",
#     "external_google_secret": "your-google-client-secret"
#   }'