-- Student registry (shared by every system) + tables for the OMR answer-sheet
-- checker that lives at /omr/ (public/omr/index.html).
--
-- students: visible/editable only by approved staff (teacher/admin); only an
--           admin may delete a row. Contains no national ID / address data.
-- omr_*:    each teacher sees only their own subjects and results.

-- ── STUDENTS ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_code text NOT NULL,
  prefix text,
  first_name text NOT NULL,
  last_name text NOT NULL DEFAULT '',
  gender text CHECK (gender IN ('ช', 'ญ')),
  class_level text NOT NULL,          -- เช่น 'ป.4', 'ม.1'
  room text,                          -- ห้อง เช่น '1'
  is_active boolean NOT NULL DEFAULT true,
  user_id uuid DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT students_student_code_key UNIQUE (student_code)
);

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Staff can read students" ON public.students;
CREATE POLICY "Staff can read students"
  ON public.students FOR SELECT
  USING (public.can_access_dashboard());

DROP POLICY IF EXISTS "Staff can add students" ON public.students;
CREATE POLICY "Staff can add students"
  ON public.students FOR INSERT
  WITH CHECK (public.can_access_dashboard());

DROP POLICY IF EXISTS "Staff can update students" ON public.students;
CREATE POLICY "Staff can update students"
  ON public.students FOR UPDATE
  USING (public.can_access_dashboard())
  WITH CHECK (public.can_access_dashboard());

DROP POLICY IF EXISTS "Admin can delete students" ON public.students;
CREATE POLICY "Admin can delete students"
  ON public.students FOR DELETE
  USING (public.is_admin());

DROP TRIGGER IF EXISTS update_students_updated_at ON public.students;
CREATE TRIGGER update_students_updated_at
  BEFORE UPDATE ON public.students
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX IF NOT EXISTS students_class_idx ON public.students (class_level, room, student_code);

-- ── OMR: SUBJECTS (answer keys) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.omr_subjects (
  id uuid PRIMARY KEY,                -- generated by the client
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  n int NOT NULL,
  k int NOT NULL,
  labels text NOT NULL,
  id_len int NOT NULL DEFAULT 5,
  key jsonb NOT NULL DEFAULT '[]',
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- ── OMR: RESULTS ────────────────────────────────────────────────────
-- student_id holds the student *code* read from the sheet (matches
-- students.student_code); it is deliberately not a foreign key so a sheet can
-- be saved even when the code is not (yet) in the registry.
CREATE TABLE IF NOT EXISTS public.omr_results (
  id uuid PRIMARY KEY,                -- generated by the client
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  subject_id uuid REFERENCES public.omr_subjects(id) ON DELETE SET NULL,
  subject_name text NOT NULL,
  student_id text NOT NULL DEFAULT '',
  student_name text NOT NULL DEFAULT '',
  score int NOT NULL,
  total int NOT NULL,
  answers jsonb NOT NULL,
  labels text NOT NULL DEFAULT 'thai',
  taken_at timestamptz NOT NULL,
  deleted_at timestamptz
);

CREATE INDEX IF NOT EXISTS omr_results_user_idx ON public.omr_results (user_id, subject_id, taken_at DESC);
CREATE INDEX IF NOT EXISTS omr_results_student_idx ON public.omr_results (student_id);

ALTER TABLE public.omr_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.omr_results ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owner manages omr subjects" ON public.omr_subjects;
CREATE POLICY "Owner manages omr subjects"
  ON public.omr_subjects FOR ALL
  USING (user_id = auth.uid() AND public.can_access_dashboard())
  WITH CHECK (user_id = auth.uid() AND public.can_access_dashboard());

DROP POLICY IF EXISTS "Owner manages omr results" ON public.omr_results;
CREATE POLICY "Owner manages omr results"
  ON public.omr_results FOR ALL
  USING (user_id = auth.uid() AND public.can_access_dashboard())
  WITH CHECK (user_id = auth.uid() AND public.can_access_dashboard());
